Repository Aymane-Arfaoui/FindMyClass, pull requests merged in 2025-04, with the labels that each got.

#310 Add Missing Android Files.
  android/.gitignore
  android/app/build.gradle
  android/app/debug.keystore
  android/app/proguard-rules.pro
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/aymanearfaoui/FindMyClass/MainActivity.kt
  android/app/src/main/java/com/aymanearfaoui/FindMyClass/MainApplication.kt
  android/app/src/main/res/drawable-hdpi/splashscreen_logo.png
  android/app/src/main/res/drawable-mdpi/splashscreen_logo.png
  android/app/src/main/res/drawable-xhdpi/splashscreen_logo.png
  android/app/src/main/res/drawable-xxhdpi/splashscreen_logo.png
  android/app/src/main/res/drawable-xxxhdpi/splashscreen_logo.png
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values-night/colors.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
Labels: backend

#312 Outdoor, Indoor Route/Map Enhancements
  api/app/data/campus_jsons/hall/map_hall_8.json
  app/MapScreen.jsx
  app/homemap.jsx
  components/BottomPanel.jsx
  components/BuildingDetailsPanel.jsx
  components/FloorSelector.jsx
  components/IndoorSearchBars.jsx
  components/SectionPanel.jsx
  components/StartPointSearchBar.jsx
  constants/floorData.js
Labels: frontend, sprint: 6

#330 Aymane google auth fix
  android/app/debug.keystore
  api/app/graph/__pycache__/graph2.cpython-313.pyc
  api/app/routes.py
  app/MapScreen.jsx
  app/Welcome.jsx
  app/homemap.jsx
  app/placeholder.jsx
  app/settingsPage.jsx
  app/user.jsx
  components/AppNavigationPannel.jsx
  components/BottomPanel.jsx
  components/BuildingDetailsPanel.jsx
  components/Calendar.jsx
  components/MainSearchBar.jsx
  components/MapButtons.jsx
  components/PlaceFilterButtons.jsx
  components/SearchBars.jsx
  constants/colorPalettes.js
  maestro/Calendar.yaml
  maestro/OutdoorDirections.yaml
  maestro/POIs.yaml
  maestro/ShuttleSched.yaml
  services/shuttleService.js
Labels: frontend, backend, refactoring
