Repository Aymane-Arfaoui/FindMyClass, pull requests merged in 2025-03, with the labels that each got.

#221 refactor indoor maps + finalize outdoor map + include shuttle
  app/MapScreen.jsx
  app/Welcome.jsx
  app/homemap.jsx
  app/shuttleSchedule.jsx
  assets/images/ConcordiaLogo.png
  components/AppNavigationPannel.jsx
  components/BottomPanel.jsx
  components/BuildingDetailsPanel.jsx
  components/FloorSlector.jsx
  components/Map.jsx
  components/SectionPanel.jsx
  constants/floorData.js
  ios/FindMyClass.xcodeproj/project.pbxproj
  ios/Podfile.lock
  services/routeService.js
  services/shuttleService.js
Labels: enhancement, frontend, sprint: 4, refactoring

#224 Update package.json to remove one jest setup
  package.json
Labels: testing, refactoring

#223 Outdoor POIs and Directions
  app/MapScreen.jsx
  app/homemap.jsx
  components/Map.jsx
  components/PlaceFilterButtons.jsx
  jest.config.js
Labels: frontend, sprint: 4

#227 minor refactoring in the code
  app/MapScreen.jsx
  app/homemap.jsx
  components/BottomPanel.jsx
  components/BuildingDetailsPanel.jsx
  components/FloorSelector.jsx
  components/SectionPanel.jsx
  services/routeService.js
Labels: refactoring

#233 Add indoor coordinates for indoor paths.
  api/app/Services/coordinate_mapper.py
  api/app/Services/coordinates.json
  api/app/Services/marked_map.png
  api/app/__init__.py
  api/app/__pycache__/__init__.cpython-313.pyc
  api/app/__pycache__/auth.cpython-313.pyc
  api/app/__pycache__/navigation.cpython-313.pyc
  api/app/__pycache__/routes.cpython-313.pyc
  api/app/__pycache__/test.cpython-313.pyc
  api/app/data/Hall_1.png
  api/app/data/Screenshot_2025-03-04_at_4.52.24_PM.png
  api/app/data/campus_jsons/cc/map_cc_1.json
  api/app/data/campus_jsons/hall/map_hall_1.json
  api/app/data/campus_jsons/hall/map_hall_2.json
  api/app/data/campus_jsons/hall/map_hall_8.json
  api/app/data/campus_jsons/hall/map_hall_9.json
  api/app/data/campus_jsons/mb/map_mb_1.json
  api/app/data/campus_jsons/mb/map_mb_s2.json
  api/app/data/image.png
  api/app/data/images/cc_1_mapped_coordinates.png
  api/app/data/images/hall_1_mapped_coordinates.png
  api/app/data/images/hall_2_mapped_coordinates.png
  api/app/data/images/hall_8_mapped_coordinates.png
  api/app/data/images/hall_9_mapped_coordinates.png
  api/app/data/images/mb_1_mapped_coordinates.png
  api/app/data/images/mb_s2_mapped_coordinates.png
  api/app/data/path.jpg
  api/app/graph/__pycache__/Graph.cpython-313.pyc
  api/app/graph/graph.py
  api/app/graph/graph_test.py
  api/app/indoor_routing.py
  api/app/navigation.py
  api/app/routes.py
  api/flask_session/2029240f6d1128be89ddc32729463129
Labels: backend, sprint: 4

#282 Fix Voice Input Bug
  android/app/src/main/AndroidManifest.xml
  app/homemap.jsx
  components/AppNavigationPannel.jsx
  components/MainSearchBar.jsx
  ios/FindMyClass.xcodeproj/project.pbxproj
  ios/FindMyClass.xcodeproj/xcshareddata/xcschemes/FindMyClass.xcscheme
  ios/FindMyClass/Info.plist
  ios/Podfile.lock
Labels: enhancement, frontend, sprint: 5

#276 Added refresh feature (button) and refresh calendar on app reload. Im…
  app/Welcome.jsx
  components/Calendar.jsx
  services/calendarService.js
Labels: enhancement, refactoring

#303 Fix Time Estimation for Google Maps API
  app/homemap.jsx
  components/BottomPanel.jsx
  components/SearchBars.jsx
  components/TransportOptions.jsx
Labels: backend
